entity: zwo_filter_wheel
library: /opt/sk/libEFWFilter.dylib
server:
  host: 0.0.0.0
  port: 5010
log_level: INFO
devices:
  - entity: EFW_1
    device_number: 0
    serial_number: ""
    names:
      - Filter_1
      - Filter_2
      - Filter_3
      - Filter_4
      - Filter_5
      - Filter_6
      - Filter_7
    focus_offsets:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    timeout: 60
    unidirectional: false
